# Generated by Django 4.1.6 on 2023-04-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_comments_options_remove_comments_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.comments'),
        ),
    ]
