# Generated by Django 4.1.6 on 2023-04-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_comments_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent_comment',
        ),
    ]
