# Generated by Django 4.1.6 on 2023-04-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_comments_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parent_comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='books.comments'),
        ),
    ]
